# TCL File Generated by Component Editor 11.0sp1
# Mon Jun 25 21:17:39 EEST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dma_source "dma_source" v1.0
# | null 2012.06.25.21:17:39
# | 
# | 
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module dma_source
# | 
set_module_property NAME dma_source
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME dma_source
set_module_property TOP_LEVEL_HDL_FILE ""
set_module_property TOP_LEVEL_HDL_MODULE dma_source
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME dma_source
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point data_slave
# | 
add_interface data_slave avalon end
set_interface_property data_slave addressAlignment DYNAMIC
set_interface_property data_slave addressUnits WORDS
set_interface_property data_slave associatedClock clock
set_interface_property data_slave associatedReset reset
set_interface_property data_slave burstOnBurstBoundariesOnly false
set_interface_property data_slave explicitAddressSpan 0
set_interface_property data_slave holdTime 0
set_interface_property data_slave isMemoryDevice false
set_interface_property data_slave isNonVolatileStorage false
set_interface_property data_slave linewrapBursts false
set_interface_property data_slave maximumPendingReadTransactions 1
set_interface_property data_slave printableDevice false
set_interface_property data_slave readLatency 0
set_interface_property data_slave readWaitTime 1
set_interface_property data_slave setupTime 0
set_interface_property data_slave timingUnits Cycles
set_interface_property data_slave writeWaitTime 0

set_interface_property data_slave ENABLED true

add_interface_port data_slave data_adr address Input 1
add_interface_port data_slave data_read read Input 1
add_interface_port data_slave data_readdata readdata Output 32
add_interface_port data_slave data_write write Input 1
add_interface_port data_slave data_writedata writedata Input 32
add_interface_port data_slave data_readdatavalid readdatavalid Output 1
add_interface_port data_slave data_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point control_slave
# | 
add_interface control_slave avalon end
set_interface_property control_slave addressAlignment DYNAMIC
set_interface_property control_slave addressUnits WORDS
set_interface_property control_slave associatedClock clock
set_interface_property control_slave associatedReset reset
set_interface_property control_slave burstOnBurstBoundariesOnly false
set_interface_property control_slave explicitAddressSpan 0
set_interface_property control_slave holdTime 0
set_interface_property control_slave isMemoryDevice false
set_interface_property control_slave isNonVolatileStorage false
set_interface_property control_slave linewrapBursts false
set_interface_property control_slave maximumPendingReadTransactions 0
set_interface_property control_slave printableDevice false
set_interface_property control_slave readLatency 0
set_interface_property control_slave readWaitTime 1
set_interface_property control_slave setupTime 0
set_interface_property control_slave timingUnits Cycles
set_interface_property control_slave writeWaitTime 0

set_interface_property control_slave ENABLED true

add_interface_port control_slave control_adr address Input 1
add_interface_port control_slave control_write write Input 1
add_interface_port control_slave control_data writedata Input 32
add_interface_port control_slave control_wait_request waitrequest Output 1
# | 
# +-----------------------------------
