onerr {resume}
add list -bin /test_bench/clk
add list -bin /test_bench/DUT/the_descf/chipselect
add list -bin /test_bench/DUT/the_descf/write
add list -hex /test_bench/DUT/the_descf/address
add list -bin /test_bench/DUT/the_descf/byteenable
add list -hex /test_bench/DUT/the_descf/readdata
add list -hex /test_bench/DUT/the_descf/writedata
add list -bin /test_bench/DUT/the_sgdma_rx/csr_read
add list -bin /test_bench/DUT/the_sgdma_rx/csr_write
add list -bin /test_bench/DUT/the_sgdma_rx/csr_address
add list -bin /test_bench/DUT/the_sgdma_rx/csr_chipselect
add list -bin /test_bench/DUT/the_sgdma_rx/csr_writedata
add list -bin /test_bench/DUT/the_sgdma_rx/csr_readdata
add list -bin /test_bench/DUT/the_onchip_memory2/chipselect
add list -bin /test_bench/DUT/the_onchip_memory2/write
add list -hex /test_bench/DUT/the_onchip_memory2/address
add list -bin /test_bench/DUT/the_onchip_memory2/byteenable
add list -hex /test_bench/DUT/the_onchip_memory2/readdata
add list -hex /test_bench/DUT/the_onchip_memory2/writedata
add list -bin /test_bench/DUT/the_descriptor_memory/chipselect
add list -bin /test_bench/DUT/the_descriptor_memory/write
add list -hex /test_bench/DUT/the_descriptor_memory/address
add list -bin /test_bench/DUT/the_descriptor_memory/byteenable
add list -hex /test_bench/DUT/the_descriptor_memory/readdata
add list -hex /test_bench/DUT/the_descriptor_memory/writedata
add list -hex /test_bench/DUT/the_sdram/az_addr
add list -hex /test_bench/DUT/the_sdram/az_be_n
add list -bin /test_bench/DUT/the_sdram/az_cs
add list -hex /test_bench/DUT/the_sdram/az_data
add list -bin /test_bench/DUT/the_sdram/az_rd_n
add list -bin /test_bench/DUT/the_sdram/az_wr_n
add list -bin /test_bench/DUT/the_sdram/clk
add list -hex /test_bench/DUT/the_sdram/za_data
add list -bin /test_bench/DUT/the_sdram/za_valid
add list -bin /test_bench/DUT/the_sdram/za_waitrequest
add list -asc /test_bench/DUT/the_sdram/CODE
add list -hex /test_bench/DUT/the_sdram/zs_addr
add list -hex /test_bench/DUT/the_sdram/zs_ba
add list -hex /test_bench/DUT/the_sdram/zs_cs_n
add list -bin /test_bench/DUT/the_sdram/zs_ras_n
add list -bin /test_bench/DUT/the_sdram/zs_cas_n
add list -bin /test_bench/DUT/the_sdram/zs_we_n
add list -hex /test_bench/DUT/the_sdram/zs_dq
add list -hex /test_bench/DUT/the_sdram/zs_dqm
add list -hex /test_bench/DUT/the_jtag_uart/av_address
add list -bin /test_bench/DUT/the_jtag_uart/av_chipselect
add list -bin /test_bench/DUT/the_jtag_uart/av_irq
add list -bin /test_bench/DUT/the_jtag_uart/av_read_n
add list -hex /test_bench/DUT/the_jtag_uart/av_readdata
add list -bin /test_bench/DUT/the_jtag_uart/av_waitrequest
add list -bin /test_bench/DUT/the_jtag_uart/av_write_n
add list -hex /test_bench/DUT/the_jtag_uart/av_writedata
add list -bin /test_bench/DUT/the_jtag_uart/dataavailable
add list -bin /test_bench/DUT/the_jtag_uart/readyfordata
add list -bin /test_bench/DUT/the_sgdma_f/csr_read
add list -bin /test_bench/DUT/the_sgdma_f/csr_write
add list -bin /test_bench/DUT/the_sgdma_f/csr_address
add list -bin /test_bench/DUT/the_sgdma_f/csr_chipselect
add list -bin /test_bench/DUT/the_sgdma_f/csr_writedata
add list -bin /test_bench/DUT/the_sgdma_f/csr_readdata
add list -hex /test_bench/DUT/the_cpu/i_readdata
add list -hex /test_bench/DUT/the_cpu/i_readdatavalid
add list -hex /test_bench/DUT/the_cpu/i_waitrequest
add list -hex /test_bench/DUT/the_cpu/i_address
add list -hex /test_bench/DUT/the_cpu/i_read
add list -hex /test_bench/DUT/the_cpu/clk
add list -hex /test_bench/DUT/the_cpu/reset_n
add list -hex /test_bench/DUT/the_cpu/d_readdata
add list -hex /test_bench/DUT/the_cpu/d_waitrequest
add list -hex /test_bench/DUT/the_cpu/d_address
add list -hex /test_bench/DUT/the_cpu/d_byteenable
add list -hex /test_bench/DUT/the_cpu/d_read
add list -hex /test_bench/DUT/the_cpu/d_write
add list -hex /test_bench/DUT/the_cpu/d_writedata
add list -hex /test_bench/DUT/the_cpu/d_irq
add list -hex /test_bench/DUT/the_cpu/d_readdatavalid
add list -hex /test_bench/DUT/the_cpu/the_cpu_test_bench/W_pcb
add list -asc /test_bench/DUT/the_cpu/the_cpu_test_bench/W_vinst
add list -hex /test_bench/DUT/the_cpu/the_cpu_test_bench/W_valid
add list -hex /test_bench/DUT/the_cpu/the_cpu_test_bench/W_iw
add list -bin /test_bench/DUT/the_sgdma_tx/csr_read
add list -bin /test_bench/DUT/the_sgdma_tx/csr_write
add list -bin /test_bench/DUT/the_sgdma_tx/csr_address
add list -bin /test_bench/DUT/the_sgdma_tx/csr_chipselect
add list -bin /test_bench/DUT/the_sgdma_tx/csr_writedata
add list -bin /test_bench/DUT/the_sgdma_tx/csr_readdata
add list -bin /test_bench/DUT/the_tse_mac/ena_10
add list -bin /test_bench/DUT/the_tse_mac/eth_mode
add list -bin /test_bench/DUT/the_tse_mac/mdc
add list -bin /test_bench/DUT/the_tse_mac/mdio_in
add list -bin /test_bench/DUT/the_tse_mac/mdio_oen
add list -bin /test_bench/DUT/the_tse_mac/mdio_out
add list -hex /test_bench/DUT/the_tse_mac/rgmii_in
add list -hex /test_bench/DUT/the_tse_mac/rgmii_out
add list -bin /test_bench/DUT/the_tse_mac/rx_clk
add list -bin /test_bench/DUT/the_tse_mac/rx_control
add list -bin /test_bench/DUT/the_tse_mac/set_10
add list -bin /test_bench/DUT/the_tse_mac/set_1000
add list -bin /test_bench/DUT/the_tse_mac/tx_clk
add list -bin /test_bench/DUT/the_tse_mac/tx_control
configure list -usestrobe 0
configure list -strobestart {0 ps} -strobeperiod {0 ps}
configure list -delta none
configure list -usegating 1
configure list -gateexpr { /test_bench/clk'rising }